#VERSION=0.1
name: CI

on: push

env:
    SVC_NAME: sk-example-app

jobs:

  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
